title: <p align="center"> Nikita Surve </p>
logo: /assets/img/WhatsApp Image 2022-02-14 at 12.21.31 AM (2).jpeg

description:
  <p align="center">|
 <a href="https://github.com/NikitaSurve">GitHub</a>|
  
  <br>   
  I'm working on Power Platform.
  Worked with Mindtree as customer support.
  Working in PowerPlatform domain for  years.
  <br>
  </p>



theme: jekyll-theme-minimal
